main = "./src/index.ts"
name = "scrummy"

compatibility_date = "2022-07-26"
compatibility_flags = ["durable_object_alarms"]

workers_dev = false

# PRODUCTION

routes = [
  { pattern = "scrummy.cards/api/*", custom_domain = false },
  { pattern = "playscrummy.com/api/*", custom_domain = false }
]
vars = { ENVIRONMENT = "production" }

[durable_objects]
bindings = [{name = "GAME", class_name = "ScrummyGame"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ScrummyGame"]

# DEV

[env.dev]
name = "scrummy-dev"
routes = [
  { pattern = "dev.scrummy.cards/api/*", custom_domain = false },
  { pattern = "dev.playscrummy.com/api/*", custom_domain = false }
]
vars = { ENVIRONMENT = "dev" }

[env.dev.durable_objects]
bindings = [{name = "GAME", class_name = "ScrummyGame"}]
