# A sample Gemfile
source "https://rubygems.org"

# We declare depdendencies at less than their next full version to ensure we don't get any breaking changes.
gem 'toolkit', '<2.0.0'
gem 'singularitygs', '<2.0.0'
gem 'breakpoint', '<3.0.0'
gem 'css_parser', '~>1.3.4'
